title: PickMy.ai
description: Pick your AI adventure from a list of popular AI-powered websites! From content generation to research, we've got you covered.
show_downloads: false
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
