title: PickMy.ai
description: Pick your AI adventure.
show_downloads: false
google_analytics: G-PZP8CJ7XRH
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
